/**
 * Service Worker — cache-first strategy for full offline capability.
 * Auto-generated by build script.
 */

const CACHE_NAME = 'beichtbar-1772873537909';

const ASSETS_TO_CACHE = [
  "/",
  "/index.html",
  "/css/app.css",
  "/js/app.js",
  "/data/questions.json",
  "/manifest.json",
  "/assets/icons/icon.svg",
  "/assets/icons/apple-touch-icon.png",
  "/assets/icons/icon-192.png",
  "/assets/icons/icon-512.png",
  "/assets/splash/1125x2436.png",
  "/assets/splash/1170x2532.png",
  "/assets/splash/1179x2556.png",
  "/assets/splash/1242x2208.png",
  "/assets/splash/1242x2688.png",
  "/assets/splash/1284x2778.png",
  "/assets/splash/1290x2796.png",
  "/assets/splash/1536x2048.png",
  "/assets/splash/1668x2388.png",
  "/assets/splash/2048x2732.png",
  "/assets/splash/750x1334.png",
  "/assets/splash/828x1792.png"
];

// Allow the active tab to trigger immediate activation of a waiting SW
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

// Install: pre-cache all local assets
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => cache.addAll(ASSETS_TO_CACHE))
      .then(() => self.skipWaiting())
  );
});

// Activate: clean up old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys
          .filter(key => key !== CACHE_NAME)
          .map(key => caches.delete(key))
      ))
      .then(() => self.clients.claim())
  );
});

// Fetch: cache-first, fall back to network
self.addEventListener('fetch', (event) => {
  // Don't cache external requests (Simon widget etc.)
  if (!event.request.url.startsWith(self.location.origin)) return;

  event.respondWith(
    caches.match(event.request)
      .then(cached => {
        if (cached) return cached;

        return fetch(event.request).then(response => {
          if (!response || response.status !== 200) return response;

          const responseClone = response.clone();
          caches.open(CACHE_NAME).then(cache => {
            cache.put(event.request, responseClone);
          });

          return response;
        });
      })
      .catch(() => {
        if (event.request.mode === 'navigate') {
          return caches.match('/index.html');
        }
      })
  );
});
