/**
 * Build script — compiles CSS (Tailwind), bundles JS (esbuild), copies static assets.
 * Usage:
 *   node scripts/build.js          # Production build (minified)
 *   node scripts/build.js --watch  # Dev mode (watch + rebuild)
 */

import { execSync, spawn } from 'node:child_process';
import { cpSync, mkdirSync, rmSync, readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const DIST = resolve(ROOT, 'dist');

const isWatch = process.argv.includes('--watch');

// --- Helpers ---

function clean() {
  rmSync(DIST, { recursive: true, force: true });
  mkdirSync(DIST, { recursive: true });
}

function copyStatic() {
  // Directories to copy as-is
  const dirs = ['data', 'assets'];
  for (const dir of dirs) {
    const src = resolve(ROOT, dir);
    if (existsSync(src)) {
      cpSync(src, resolve(DIST, dir), { recursive: true });
    }
  }

  // Individual files
  const files = ['manifest.json', 'robots.txt', 'sitemap.xml', '_redirects'];
  for (const file of files) {
    const src = resolve(ROOT, file);
    if (existsSync(src)) {
      cpSync(src, resolve(DIST, file));
    }
  }

  // Copy and process index.html (already updated to use compiled CSS)
  cpSync(resolve(ROOT, 'index.html'), resolve(DIST, 'index.html'));
}

function generateServiceWorker() {
  const version = `beichtbar-${Date.now()}`;

  // Collect splash screen files
  const splashDir = resolve(ROOT, 'assets', 'splash');
  const splashFiles = existsSync(splashDir)
    ? readdirSync(splashDir).filter(f => f.endsWith('.png')).map(f => `/assets/splash/${f}`)
    : [];

  const assets = [
    '/',
    '/index.html',
    '/css/app.css',
    '/js/app.js',
    '/data/questions.json',
    '/manifest.json',
    '/assets/icons/icon.svg',
    '/assets/icons/apple-touch-icon.png',
    '/assets/icons/icon-192.png',
    '/assets/icons/icon-512.png',
    ...splashFiles,
  ];

  const sw = `/**
 * Service Worker — cache-first strategy for full offline capability.
 * Auto-generated by build script.
 */

const CACHE_NAME = '${version}';

const ASSETS_TO_CACHE = ${JSON.stringify(assets, null, 2)};

// Allow the active tab to trigger immediate activation of a waiting SW
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

// Install: pre-cache all local assets
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then(cache => cache.addAll(ASSETS_TO_CACHE))
      .then(() => self.skipWaiting())
  );
});

// Activate: clean up old caches
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys
          .filter(key => key !== CACHE_NAME)
          .map(key => caches.delete(key))
      ))
      .then(() => self.clients.claim())
  );
});

// Fetch: cache-first, fall back to network
self.addEventListener('fetch', (event) => {
  // Don't cache external requests (Simon widget etc.)
  if (!event.request.url.startsWith(self.location.origin)) return;

  event.respondWith(
    caches.match(event.request)
      .then(cached => {
        if (cached) return cached;

        return fetch(event.request).then(response => {
          if (!response || response.status !== 200) return response;

          const responseClone = response.clone();
          caches.open(CACHE_NAME).then(cache => {
            cache.put(event.request, responseClone);
          });

          return response;
        });
      })
      .catch(() => {
        if (event.request.mode === 'navigate') {
          return caches.match('/index.html');
        }
      })
  );
});
`;

  writeFileSync(resolve(DIST, 'sw.js'), sw);
  // Also write to root so it's served correctly (Cloudflare serves from root)
  writeFileSync(resolve(ROOT, 'sw.js'), sw);
}

function buildCSS() {
  const input = resolve(ROOT, 'css/app.css');
  const output = resolve(DIST, 'css/app.css');
  mkdirSync(dirname(output), { recursive: true });

  const minifyFlag = isWatch ? '' : '--minify';
  execSync(
    `npx @tailwindcss/cli -i "${input}" -o "${output}" ${minifyFlag}`.trim(),
    { cwd: ROOT, stdio: 'inherit' }
  );
}

function buildJS() {
  const entry = resolve(ROOT, 'js/app.js');
  const outfile = resolve(DIST, 'js/app.js');
  mkdirSync(dirname(outfile), { recursive: true });

  const flags = [
    `--bundle`,
    `--format=esm`,
    `--outfile="${outfile}"`,
    `--target=es2020`,
  ];

  if (!isWatch) {
    flags.push('--minify');
  }

  execSync(
    `npx esbuild "${entry}" ${flags.join(' ')}`,
    { cwd: ROOT, stdio: 'inherit' }
  );
}

// --- Watch mode ---

function watchMode() {
  console.log('\n🔄 Watch mode — rebuilding on changes...\n');

  // Tailwind CSS watch (runs in background)
  const cssInput = resolve(ROOT, 'css/app.css');
  const cssOutput = resolve(DIST, 'css/app.css');
  mkdirSync(dirname(cssOutput), { recursive: true });

  const tailwind = spawn(
    'npx',
    ['@tailwindcss/cli', '-i', cssInput, '-o', cssOutput, '--watch'],
    { cwd: ROOT, stdio: 'inherit', shell: true }
  );

  // esbuild watch (runs in background)
  const jsEntry = resolve(ROOT, 'js/app.js');
  const jsOut = resolve(DIST, 'js/app.js');
  mkdirSync(dirname(jsOut), { recursive: true });

  const esbuild = spawn(
    'npx',
    ['esbuild', jsEntry, '--bundle', '--format=esm', `--outfile=${jsOut}`, '--target=es2020', '--watch'],
    { cwd: ROOT, stdio: 'inherit', shell: true }
  );

  // Handle termination
  process.on('SIGINT', () => {
    tailwind.kill();
    esbuild.kill();
    process.exit(0);
  });
}

// --- Main ---

console.log(isWatch ? '🔧 Building (dev)...' : '📦 Building (production)...');

clean();
copyStatic();
buildCSS();
buildJS();
generateServiceWorker();

if (isWatch) {
  watchMode();
} else {
  // Report output size
  const cssSize = readFileSync(resolve(DIST, 'css/app.css')).length;
  const jsSize = readFileSync(resolve(DIST, 'js/app.js')).length;
  console.log(`\n✅ Build complete → dist/`);
  console.log(`   CSS: ${(cssSize / 1024).toFixed(1)} KB`);
  console.log(`   JS:  ${(jsSize / 1024).toFixed(1)} KB`);
}
